#!/usr/bin/env bash

n=1
while [ $n -le 100 ];
do
	echo $n
	if (( n % 15 == 0 ));then
		echo "FizzBuzz"
	elif (( n % 3 == 0 ));then
		echo "Fizz"
	elif (( n % 5 == 0 ));then
		echo "Buzz"
	else
		echo $n
	fi
	((n++))
done
