#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".


n=1
while [ $n -le 10 ];
do
	echo 'Best School'
	if [ $n == 9 ];
	then
		echo 'Hi'
	fi
	((n++))
done
