#!/usr/bin/env bash

n=1
while [ $n -le 20 ];
do
	if [ $n == 4 ];
	then
		echo 'bad luck fron China'
	elif [ $n == 9 ];
	then
		echo 'bad luck from Japan'
	elif [ $n == 17 ];
	then
		echo 'bad luck from Italy'
	else
		echo $n
	fi
	((n++))
done
