#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration


n=1
while [ $n -le 20 ];
do
	if [ $n == 4 ];
	then
		echo 'bad luck fron China'
	elif [ $n == 9 ];
	then
		echo 'bad luck from Japan'
	elif [ $n == 17 ];
	then
		echo 'bad luck from Italy'
	else
		echo $n
	fi
	((n++))
done
